parameters:
  - name: envType
    displayName: env type
    type: string
    default: dev
    values:
      - dev
      - staging
      - prod

  - name: instanceNo
    displayName: instance number (1-9)?
    type: string
    default: "1"

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: rest-app-infra-group
  - name: backendAzureRmKey
    value: rest${{ parameters.envType }}no${{ parameters.instanceNo }}.terraform.tfstate
  - name: workingDirectory
    value: "$(Build.SourcesDirectory)/terraform/RestWebApp"

stages:
  - stage:
    jobs:
      - job: destroy
        steps:
          - task: TerraformInstaller@1
            displayName: terraform install
            inputs:
              terraformVersion: "latest"
          - task: TerraformTaskV3@3
            displayName: init
            inputs:
              provider: "azurerm"
              command: "init"
              backendServiceArm: "$(defaultServiceName)"
              backendAzureRmResourceGroupName: "$(backendAzureRmResourceGroupName)"
              backendAzureRmStorageAccountName: "$(backendAzureRmStorageAccountName)"
              backendAzureRmContainerName: "$(backendAzureRmContainerName)"
              backendAzureRmKey: "$(backendAzureRmKey)"
              workingDirectory: "$(workingDirectory)"
          - task: TerraformTaskV3@3
            displayName: destroy
            inputs:
              provider: "azurerm"
              command: "destroy"
              environmentServiceNameAzureRM: "$(defaultServiceName)"
              workingDirectory: "$(workingDirectory)"
