trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: rest-app-infra-group
  - name: workingDirectory
    value: "$(Build.SourcesDirectory)/terraform/RestAppInfra"

stages:
  - stage:
    jobs:
      - job: destroy
        steps:
          - task: TerraformInstaller@1
            displayName: terraform install
            inputs:
              terraformVersion: "latest"
          - task: TerraformTaskV3@3
            displayName: init
            inputs:
              provider: "azurerm"
              command: "init"
              backendServiceArm: "$(defaultServiceName)"
              backendAzureRmResourceGroupName: "$(backendAzureRmResourceGroupName)"
              backendAzureRmStorageAccountName: "$(backendAzureRmStorageAccountName)"
              backendAzureRmContainerName: "$(backendAzureRmContainerName)"
              backendAzureRmKey: "$(backendAzureRmKey)"
              workingDirectory: "$(workingDirectory)"
          - task: TerraformTaskV3@3
            displayName: destroy
            inputs:
              provider: "azurerm"
              command: "destroy"
              environmentServiceNameAzureRM: "$(defaultServiceName)"
              workingDirectory: "$(workingDirectory)"
